### ISSUE TITLE
ファイル名がユニコードのシンボリックリンク

### ISSUE THREAD

**Issue by oharas** [kobake/lnhdr#9]

**Comment by oharas** [comment]
lnhdrlink.exeで、CreateSymbolicLinkがANSIのほうで呼ばれてるようです

[DllImport("kernel32.dll", CharSet = CharSet.Auto)]

で大丈夫みたいです。

**Comment by kobake** [comment]
反応遅くなってすみませぬ!!!!! 今から見ますーー

**Comment by kobake** [comment]
遅くなりましたが対応しました。ご報告および対応方法のご教授ありがとうございました！
